# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.7
dist: bionic
sudo: required
cache: pip
branches:
  only:
  - master
before_install:
  - sudo apt-get update
  - sudo apt-get -y install sassc texlive texlive-full
script:
- cd business_theme/static/styles/
- sassc main.scss main.css
- ls -l
- cd ../../../
- python setup.py develop
- cd docs/
- pip install -r requirements.txt
- make pdf
- cd ../
- make dist
- mv docs/*.pdf dist/demo.pdf

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
