language: python
python:
  - 3.7
dist: bionic
sudo: required
cache: pip
branches:
  only:
  - master
before_install:
  - sudo apt-get update
  - sudo apt-get -y install sassc texlive texlive-full
script:
- cd business_theme/static/styles/
- sassc main.scss main.css
- ls -l
- cd ../../../
- python setup.py develop
- cd demo/
- pip install -r requirements.txt
- make pdf
- cd ../
- cd docs/
- pip install -r requirements.txt
- make pdf
- cd ../
- make dist
- mv demo/*.pdf dist/demo.pdf
- mv docs/*.pdf dist/docs.pdf
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
  - provider: pypi
    user: __token__
    password:
      secure: 5nc5niIxpLhIgG/GWcovKuCAFHBu/xhHS8GhBZmnvGiGg6Hti0k41+cr3XcckotaKeVcvoSuLFyHygYe8xFjSGa8ebFvH92VEZ5DRqUPkMWkF5bRUTTLyWTD6mvScJ0lDuGnUWOI6Cn9r/qdaoeIfu1u/3xWoY+A9j5pMTcTSY0Ccb0J3ryZu4i8Ez5FbZz2kiHL/VVHLPL+EHVSNLZHpAj1SdDFqxq8wEIC+jJ0f1mC/J8xmwNXHvA1rK8YploB9M1aYkTzGUaBNMIS1EXsQJhJKFcJu48Iz4rDE1khlox9Elm4N6lR3Abq26inB9fSt8Al4atFFU/fA375GMTUc15RX8+t1x4XIWV3c5Is+/hUAGAqaLiUXmLSwUriLwht357p8LMqEexeKjK6oWLW7kFzQ/gePNM/9IBT3PdV7oyu+cUEvGIVFMhxyHGuNOJ861AuBoHbC3nB67eKwHP6o8mbjFjEiWiqaYUqBQW8a0mvspgtR016iK1lMbotSOJZmhDJPmAK7ADpVkqcBHsH2yKJhdGRHZFBQXfILNTgUvkBuN27DLJeuhfPYE6MPmcI2X+wH/mynJoFvc1ky4j2eEmv+IqPcszeXcW0WSN1rBCQcN8RVK9F8c7cMSRWNoo0rhXbiyUvDiuCgYV2C46TopYYMYTL8vH4KSXiae06ZWg=
    on:
      tags: true
